//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPoject.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_de_stockEntities2 : DbContext
    {
        public gestion_de_stockEntities2()
            : base("name=gestion_de_stockEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brande> brandes { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<costumer> costumers { get; set; }
        public virtual DbSet<funded> fundeds { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<transfer_details> transfer_details { get; set; }
        public virtual DbSet<type_user> type_user { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
