//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPoject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_costumer { get; set; }
        public Nullable<int> id_user { get; set; }
        public string pay_type { get; set; }
        public decimal price_sall_final { get; set; }
        public int quantity { get; set; }
        public string state { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> end_in { get; set; }
    
        public virtual costumer costumer { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
