//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPoject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orders = new HashSet<order>();
            this.transfer_details = new HashSet<transfer_details>();
        }
    
        public int id { get; set; }
        public string code_bar { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string product_image { get; set; }
        public decimal price_bay { get; set; }
        public decimal price_sall { get; set; }
        public int quntity { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_brande { get; set; }
        public Nullable<int> id_store { get; set; }
        public Nullable<int> id_funded { get; set; }
    
        public virtual brande brande { get; set; }
        public virtual category category { get; set; }
        public virtual funded funded { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer_details> transfer_details { get; set; }
        public virtual store store { get; set; }
    }
}
