//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPoject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer_details
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int store_from { get; set; }
        public int store_to { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> transform_date { get; set; }
    
        public virtual product product { get; set; }
        public virtual store store { get; set; }
        public virtual store store1 { get; set; }
    }
}
